version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: your_database_name
    volumes:
      - db_data:/var/lib/postgresql/data  # 永続的なデータ保存に適したボリューム

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - ".:/app"
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/your_database_name

volumes:
  db_data:  # ボリュームの定義
